version: "3"

services:
  python_app:
    build: .
    command: python src/air_quality_app/streaming.py
    volumes:
      - .:/app
    privileged: true
    devices:
      - "/dev:/dev"
    depends_on:
      - influxdb

  influxdb:
    image: arm32v7/influxdb:latest
    container_name: influxdb
    restart: always
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
    - INFLUXDB_ADMIN_USER=influxdb
    - INFLUXDB_ADMIN_PASSWORD=influxdb
    - INFLUXDB_REPORTING_DISABLED=true
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_ANALYTICS_REPORTING_ENABLED=false

volumes:
  influxdb-storage:
  grafana-storage: