name: air_quality_app
channels:
  - conda-forge
dependencies:
  - black
  - ipykernel
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python==3.8.*
  - scikit-learn
  - scipy
  - seaborn
  
