{
 "title": "Air Quality Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "retention",
    "query": "short_term_retention, history_15m"
   }
  ]
 },
 "panels": [
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "query": "SELECT mean(\"PM2.5\") AS \"PM2.5\", mean(\"PM10\") AS \"PM10\" FROM \"$retention\".\"air_quality\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PM2.5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM2.5" ], "type": "alias" }
      ],
      [
       { "params": [ "PM10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PM10" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(mean(\"PM10\"), 60) + 32 FROM \"$retention\".\"air_quality\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Smoke Detector",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "alias": "Level:",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT -1*(moving_average(mean(\"PM10\"), 60) + 32 - mean(\"PM10\")) FROM \"$retention\".\"air_quality\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" },
       { "params": [ "humidity_ma5" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "Humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Volatile Organic Compounds (TVOC)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "TVOC_ugm3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "TVOC" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Formaldehyde",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "CH20_ugm3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "air_quality",
     "select": [
      [
       { "params": [ "CO2_ppm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT moving_average(mean(\"CO2_ppm\"), 120) FROM \"$retention\".\"air_quality\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}